import Head from 'next/head'
import React from 'react'
import Layout from '../components/global/Layout'
import DesignES from '../content/es/design.json';

import ServiceHero from '../components/pages/sections/ServiceHero';
import BlackDescription from '../components/pages/sections/BlackDescription';
import ServiceCharacteristics from '../components/pages/sections/ServiceCharacteristics';
const identidadVisual = () => {

    const { hero, description, services } = DesignES;
  return (
    <div>
        <Head>
        <title>Diseño de image de marca</title>
        <meta name="description" content="Generated by create next app" />
        </Head>

        <Layout>
            <ServiceHero hero={hero} />
            <BlackDescription description={description} />
            <ServiceCharacteristics services={services}/>
        </Layout>

    </div>
  )
}

export default identidadVisual