import Head from "next/head";
import Image from "next/image";
import Layout from "../components/global/Layout";

import HomerES from "../content/es/home.json";
import Link from "next/link";
import Hero from "../components/pages/home/Hero";
import Services from "../components/pages/home/Services";

export default function Home() {
    const { hero, services, blog } = HomerES;

    return (
        <div>
            {/* {Debo crear un componente aparte para el head} */}
            <Head>
                <title>Agencia de desarrollo web</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Hero hero={hero} />

                <Services services={services} />
            </Layout>
        </div>
    );
}
