import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/global/Layout'

import HomerES from '../content/es/home.json';
import Link from 'next/link';
export default function Home() {

  const { hero, services, blog } = HomerES;

  return (
    <div >
      {/* {Debo crear un componente aparte para el head} */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <Layout>
        <section className="home-hero__section">
          <div className="home-hero__left">
            <h1>{hero.title}<span className="point-orange">.</span></h1>
            <p>{hero.sutitle}</p>
            <Link href={hero.cta.url}>
              <a>{hero.cta.title}</a>
            </Link>
          </div>
          <div className="home-hero__right">
            <img className="home-hero__img" src={hero.img.src} alt={hero.img.alt} />
            <div className="home-hero__card">
              <div>
                <span>+</span>
                <h6>200%</h6>
                <p>{hero.card}</p>
              </div>
              <svg width="261" height="113" viewBox="0 0 261 113" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M32.6382 66.5695C13.0584 69.3178 1 88.1821 1 88.1821V112H243.83C243.83 112 280.652 7.81581 243.83 1.32834C214.152 -3.90038 206.153 55.0238 175.843 56.8659C156.934 58.0151 137.947 43.8718 119.227 46.2801C100.545 48.6835 105.792 69.4332 87.0336 71.4213C69.4949 73.2801 50.0624 64.1238 32.6382 66.5695Z" fill="url(#paint0_linear_1144_4)" stroke="#F84525"/>
<defs>
<linearGradient id="paint0_linear_1144_4" x1="122.969" y1="21.5303" x2="122.969" y2="112" gradientUnits="userSpaceOnUse">
<stop stopColor="#F84525"/>
<stop offset="1" stopColor="#FFC300" stopOpacity="0"/>
</linearGradient>
</defs>
</svg>
            </div>
          </div>
        </section>


        <section className="home-services__section" >
          <h6>{services.top_title}</h6>
          <h2>{services.title}</h2>
          <div className="home-services__list">
            {
              services.list.map((item, key)=> {
                return(
                  <div key={key} className="home-services__item">
                    <div>
                      <h6>{item.top_title}</h6>
                      <h3>{item.title}<span className="point-orange">.</span></h3>
                      <p>{item.content}</p>
                      <a>{item.cta.title}</a>
                    </div>
                  </div>
                )
              })
            }
          </div>

        </section>

        <section className="home-blog__section">
            <h6>{blog.top_title}</h6>
            <h2>{blog.title}<span className="point-orange">.</span></h2>
            <div className="home-blog__list">
              {
                blog.list.map((element,index)=> {
                  return(
                    <div key={index} className="home-blog__article">
                      <img src={element.img.src} alt={element.img.alt} />
                      
                      <div>
                        <h3>{element.title}</h3>
                        <span>{element.date}</span>
                        <a>{element.cta.title}</a>
                      </div>



                    </div>
                  )
                })
              }
            </div>
        </section>
      </Layout>
    </div>
  )
}
