import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/global/Layout'

import HomerES from '../content/es/home.json';
import Link from 'next/link';
export default function Home() {

  const { hero, services, blog } = HomerES;

  return (
    <div >
      {/* {Debo crear un componente aparte para el head} */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <Layout>
        

        <section className="home-hero">
          <div className="home-container">
            <h1 >Soluciones digitales <br/><span className="orange-text">al alcance de tu empresa</span><span className="point-orange">.</span></h1>
            <p>Nos dedicamos al diseño de desarrollo de soluciones digitales para empresas que buscan crecer aprovechando canales digitales.</p>
<Link href="/contact">
              <a >Solicitar presupuesto</a>
</Link>
             
          </div>
          <svg width="220" height="220" viewBox="0 0 220 220" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_981_84)">
<rect x="7" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="107" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="27" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="127" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="47" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="147" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="67" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="167" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="87" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="187" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="207" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="7" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="107" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="27" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="127" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="47" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="147" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="67" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="167" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="87" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="187" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="207" y="24" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="7" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="107" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="27" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="127" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="47" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="147" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="67" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="167" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="87" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="187" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="207" y="48" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="7" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="107" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="27" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="127" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="47" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="147" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="67" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="167" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="87" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="187" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="207" y="72" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="7" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="107" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="27" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="127" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="47" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="147" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="67" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="167" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="87" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="187" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="207" y="92" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="7" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="107" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="27" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="127" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="47" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="147" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="67" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="167" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="87" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="187" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="207" y="116" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="7" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="107" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="27" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="127" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="47" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="147" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="67" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="167" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="87" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="187" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="207" y="140" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="7" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="107" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="27" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="127" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="47" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="147" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="67" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="167" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="87" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="187" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="207" y="164" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="9" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="109" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="29" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="129" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="49" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="149" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="69" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="169" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="89" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="189" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="209" y="184" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="9" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="109" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="29" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="129" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="49" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="149" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="69" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="169" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="89" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="189" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
<rect x="209" y="208" width="5" height="5" rx="2.5" fill="#F84525"/>
</g>
<defs>
<clipPath id="clip0_981_84">
<rect width="220" height="220" rx="110" fill="white"/>
</clipPath>
</defs>
</svg>

        </section>

        <section className="home-services">
          {
            services.list.map((service, i) => (
              <div key={i} className="home-service">
                <img src={service.img.src} alt={service.img.alt} />

                <div className="home-service__card">
                  {/* <span>{service.top_title}</span> */}
                  <img src={service.icon.url} alt={service.icon.alt} />
                  <h2>{service.title}</h2>
                  <p>{service.content}</p>
                  <Link href={service.cta.url}>
                  <a className="btn-secondary">{service.cta.title}</a>
                  </Link>
                </div>

              </div>
            ))
          }

        </section>
      
      </Layout>
    </div>
  )
}
